// File generated by FlutterFire CLI.
// To update, run: `flutterfire configure`

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      case TargetPlatform.web:
        return web;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'TODO: YOUR_ANDROID_API_KEY',
    appId: 'TODO: YOUR_ANDROID_APP_ID',
    messagingSenderId: 'TODO: YOUR_ANDROID_MESSAGING_SENDER_ID',
    projectId: 'TODO: YOUR_PROJECT_ID',
    storageBucket: 'TODO: YOUR_ANDROID_STORAGE_BUCKET',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'TODO: YOUR_IOS_API_KEY',
    appId: 'TODO: YOUR_IOS_APP_ID',
    messagingSenderId: 'TODO: YOUR_IOS_MESSAGING_SENDER_ID',
    projectId: 'TODO: YOUR_PROJECT_ID',
    storageBucket: 'TODO: YOUR_IOS_STORAGE_BUCKET',
    iosClientId: 'TODO: YOUR_IOS_CLIENT_ID',
    iosBundleId: 'TODO: YOUR_IOS_BUNDLE_ID',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'TODO: YOUR_MACOS_API_KEY',
    appId: 'TODO: YOUR_MACOS_APP_ID',
    messagingSenderId: 'TODO: YOUR_MACOS_MESSAGING_SENDER_ID',
    projectId: 'TODO: YOUR_PROJECT_ID',
    storageBucket: 'TODO: YOUR_MACOS_STORAGE_BUCKET',
    iosClientId: 'TODO: YOUR_MACOS_CLIENT_ID',
    iosBundleId: 'TODO: YOUR_MACOS_BUNDLE_ID',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'TODO: YOUR_WINDOWS_API_KEY',
    appId: 'TODO: YOUR_WINDOWS_APP_ID',
    messagingSenderId: 'TODO: YOUR_WINDOWS_MESSAGING_SENDER_ID',
    projectId: 'TODO: YOUR_PROJECT_ID',
    authDomain: 'TODO: YOUR_AUTH_DOMAIN',
    storageBucket: 'TODO: YOUR_WINDOWS_STORAGE_BUCKET',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'TODO: YOUR_LINUX_API_KEY',
    appId: 'TODO: YOUR_LINUX_APP_ID',
    messagingSenderId: 'TODO: YOUR_LINUX_MESSAGING_SENDER_ID',
    projectId: 'TODO: YOUR_PROJECT_ID',
    authDomain: 'TODO: YOUR_AUTH_DOMAIN',
    storageBucket: 'TODO: YOUR_LINUX_STORAGE_BUCKET',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'TODO: YOUR_WEB_API_KEY',
    appId: 'TODO: YOUR_WEB_APP_ID',
    messagingSenderId: 'TODO: YOUR_WEB_MESSAGING_SENDER_ID',
    projectId: 'TODO: YOUR_PROJECT_ID',
    authDomain: 'TODO: YOUR_AUTH_DOMAIN',
    storageBucket: 'TODO: YOUR_WEB_STORAGE_BUCKET',
    measurementId: 'TODO: YOUR_WEB_MEASUREMENT_ID',
  );
}


