name: family_travel_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.7.7
  google_sign_in: ^6.2.1
  firebase_analytics: ^10.10.7
  firebase_crashlytics: ^3.5.7
  firebase_app_check: ^0.2.2+7

  # State Management
  flutter_riverpod: ^2.5.1
  hooks_riverpod: ^2.5.1

  # Routing
  go_router: ^14.0.0

  # Offline Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Utilities
  uuid: ^4.3.3
  path_provider: ^2.1.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  image: ^4.1.7 # For image optimization
  intl: ^0.19.0 # For currency formatting
  connectivity_plus: ^6.1.4 # For network connectivity checks
  image_picker: ^1.1.2 # For picking images from gallery/camera
  # For Memory module
  cached_network_image: ^3.3.1
  flutter_staggered_grid_view: ^0.7.0
  infinite_scroll_pagination: ^4.0.0
  lottie: ^3.1.0
  photo_view: ^0.14.0
  chewie: ^1.7.4
  video_player: ^2.8.6
  image_gallery_saver: ^2.0.3
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  build_runner: ^2.4.8
  hive_generator: ^2.0.1
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  mockito: ^5.4.4
  analyzer: ^6.4.1

flutter:
  uses-material-design: true

  assets:
    - assets/


